import {
  lucideFoldHorizontal,
  lucideHome,
  lucideSettings,
  lucideUnfoldHorizontal,
  lucideArrowRightFromLine,
  lucideHelpCircle,
  lucideChevronsUpDown,
  lucideCode,
  lucideContainer,
  lucideUserRoundCog,
  lucidePencilLine,
  lucidePencilOff,
  lucideLightbulb,
  lucideBook,
  lucidePackage,
  lucideTestTubeDiagonal,
  lucideWrench,
  lucideLink,
  lucideExternalLink,
  lucideFlaskConical,
  lucidePlay,
  lucideCircleSlash,
  lucideX,
  lucideChessKing,
  lucideFileCheck,
  lucideNewspaper,
  lucideCheckCircle,
  lucideVoicemail,
} from '@ng-icons/lucide';

export const icons = {
  lucideHome,
  lucideSettings,
  lucideCode,
  lucideFoldHorizontal,
  lucideUnfoldHorizontal,
  lucideArrowRightFromLine,
  lucideHelpCircle,
  lucideChevronsUpDown,
  lucideContainer,
  lucideUserRoundCog,
  lucidePencilLine,
  lucidePencilOff,
  lucideLightbulb,
  lucideBook,
  lucidePackage,
  lucideTestTubeDiagonal,
  lucideWrench,
  lucideLink,
  lucideExternalLink,
  lucideFlaskConical,
  lucidePlay,
  lucideCircleSlash,
  lucideX,
  lucideChessKing,
  lucideFileCheck,
  lucideCheckCircle,
  lucideNewspaper,
  lucideVoicemail,
} as const;

export type IconName = keyof typeof icons;
